Taztingo/1008 upgrade ibc to v5
provenance-io/provenance pull request #1022
Opened 2022-08-18 15:20 UTC by Taztingo

## Description

This upgrades IBCv2 -> IBCv5 following the currently published migration steps.

IBCv2 -> IBCv3: This includes ICS-27. I updated Provenance to use interchain accounts (ICA), and to initialize only the host portion of it. I do not add controller support because we have not implemented an IBC auth module to control an ICA on another chain.

IBCv3 -> IBCv4: We used IBCv2.3 and do not need to include the fix for slash denoms. This was already included in 2.3.

IBCv4 -> IBCv5: This is currently in beta, and migration steps may need to change in the future.

Note: An issue will need to be created to discuss the supported host messages. Another issue will need to be created for controller support.

closes: #1008

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2022-08-23 20:29 UTC, nullpointer0x00 requested changes
Did you run this locally with an upgrade proposal?

2022-08-23 20:32 UTC, Taztingo commented
Yes, this was ran with your test scripts. Here is the output of the migration

```
3:11PM INF applying upgrade "neoncarrot-rc1" at height: 500
3:11PM INF Initializing ICA
3:11PM INF created new capability module=ibc name=ports/icahost
3:11PM INF port binded module=x/ibc/port port=icahost
3:11PM INF claimed capability capability=2 module=icahost name=ports/icahost
3:11PM INF Finished initializing ICA
```

I also verified that I was able to interact with the ica module, and I checked to see if the host params were updated.

2022-08-23 20:38 UTC, nullpointer0x00 approved these changes

2022-09-16 16:49 UTC, iramiller reviewed
minor cleanup of some of the scripts for safety...

2022-09-16 16:49 UTC, iramiller commented on scripts/install-relayer.sh
> +    cd $DIR
double quotes around $DIR to prevent issues with spaces in the path splitting the args

2022-09-16 16:49 UTC, iramiller commented on scripts/install-relayer.sh
> +    cd /tmp/relayer
if the checkout/directory creation may fail ...  add `|| exit 1 ` to halt the script with an error here.

2022-09-16 16:49 UTC, iramiller commented on scripts/install-relayer.sh
> +    rm $RELAYER_CONFIG
double quote this arg to prevent splitting

2022-09-16 16:49 UTC, iramiller commented on scripts/install-relayer.sh
> +cp $PROVENANCE_CONFIG $RELAYER_CONFIG
again, double quote `$RELAYER_CONFIG` to prevent splitting issues.

2022-09-16 16:49 UTC, iramiller commented on scripts/start-relayer.sh
> +    rly keys show $CHAIN &> /dev/null
double quotes around `$CHAIN` are required here

2022-09-16 16:49 UTC, iramiller commented on scripts/start-relayer.sh
> +check_keys ${CHAIN_1}
quote values on this line as well as 27 and 33.

2022-09-19 18:03 UTC, Taztingo commented
Looks like some of my changes from another branch got merged in here by mistake Sorting through the issues now.

2022-09-19 18:17 UTC, closed without merging