Update ibc-go to v6.1
provenance-io/provenance pull request #1278
Opened 2022-12-23 17:24 UTC by Taztingo

## Description

Updates ibc-go/v5 to ibc-go/v6. This should only be merged in after #1265 has been merged in as we use cosmos 46.7. 

closes: #1273 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2022-12-29 16:15 UTC, nullpointer0x00 requested changes
Looks good, but is missing changelog entry.

2023-01-04 17:23 UTC, nullpointer0x00 approved these changes
LGTM

2023-01-06 13:58 UTC, Taztingo commented
> @Taztingo a question on this please.. Is there a reason for keeping `SendTransfer` : https://github.com/provenance-io/provenance/blob/main/x/marker/keeper/marker.go#L737 vs using `MsgTransfer`: [cosmos/ibc-go#2446](https://github.com/cosmos/ibc-go/pull/2446)

Initially, that's what I tried. However, there is validation done that prevents us from sending the marker. We need to bypass one of those checks so I had to call SendTransfer directly.

2023-01-06 21:32 UTC, nullpointer0x00 approved these changes

2023-01-06 21:32 UTC, merged