Assign port 9091 for ibcnet ibc1 to allow reaching grpc
provenance-io/provenance pull request #1314
Opened 2023-01-20 17:35 UTC by tbrooks-figure

## Description

Add a port forward for the ibc1 docker container to allow reaching its grpc port. This is intended to better allow testing for apps that need to talk to both a private and public zone directly.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [X] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [X] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2023-01-20 18:20 UTC, derekadams approved these changes

2023-01-20 18:36 UTC, Taztingo submitted a review, later dismissed

2023-01-20 19:08 UTC, nullpointer0x00 approved these changes

2023-01-23 18:31 UTC, arnabmitra submitted a review, later dismissed

2023-01-24 14:08 UTC, nullpointer0x00 requested changes
Does this item need a change log?

2023-01-24 17:37 UTC, derekadams approved these changes

2023-01-24 17:47 UTC, Taztingo approved these changes

2023-01-24 18:09 UTC, merged