Return SDK errors from Metadata module
provenance-io/provenance pull request #1327
Opened 2023-01-29 13:42 UTC by llama-del-rey

## Description

closes: #978 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2023-02-07 15:14 UTC, nullpointer0x00 commented on x/metadata/keeper/msg_server.go
> +		return nil, sdkerrors.ErrInvalidRequest.Wrapf("scope not found with id %s", msg.ScopeId)
Should keep not found constant with how you are doing it above with `sdkerrors.ErrNotFound.Wrapf`

2023-02-07 15:14 UTC, nullpointer0x00 commented on x/metadata/keeper/msg_server.go
> +		return nil, sdkerrors.ErrInvalidRequest.Wrapf("scope not found with id %s", msg.ScopeId)
Same here: `sdkerrors.ErrNotFound.Wrapf`

2023-02-07 15:15 UTC, nullpointer0x00 commented on x/metadata/keeper/msg_server.go
> +		return nil, sdkerrors.ErrInvalidRequest.Wrapf("scope not found with id %s", msg.ScopeId)
Same here: `sdkerrors.ErrNotFound.Wrapf`

2023-02-07 15:22 UTC, nullpointer0x00 commented on x/metadata/keeper/query_server.go
> +			return &retval, sdkerrors.ErrNotFound.Wrapf("record %s does not have name %s", recordAddr, req.Name)
Should this be: `sdkerrors.ErrInvalidRequest`. I see you are using Invalid request in other areas in the query server for checks like this that fail?  Or should those others be changed? Example: ```		recordAddr2 := scopeAddr.MustGetAsRecordAddress(req.RecordName)
		if recordAddr.Empty() {
			recordAddr = recordAddr2
		} else if !recordAddr.Equals(recordAddr2) {
			return &retval, sdkerrors.ErrNotFound.Wrapf("record %s does not have name %s", recordAddr, req.RecordName)
		} ```

2023-02-07 15:23 UTC, nullpointer0x00 requested changes
I had a few comments.  Everything else looks good.

2023-04-12 15:47 UTC, SpicyLemon commented
I've copied this branch into our repo: [llama/wrap-into-sdkerrors](https://github.com/provenance-io/provenance/compare/llama/wrap-into-sdkerrors). At some point, we can pick this back up and get it across the finish line. For now, I'm going to close this PR.

2023-04-12 15:47 UTC, closed without merging