V1 add marker proposal
provenance-io/provenance pull request #1358
Opened 2023-02-09 18:56 UTC by llama-del-rey

## Description

closes: #1287

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2023-02-13 18:43 UTC, SpicyLemon commented on CHANGELOG.md
> +* Migrate `AddMarkerProposal` to v1 message based gov proposal [PR 1321](https://github.com/provenance-io/provenance/pull/1321)
When fixing the conflicts here, make sure to add an empty line after the heading and before the entries.

2023-02-13 18:44 UTC, SpicyLemon commented on CHANGELOG.md
> +* Migrate `AddMarkerProposal` to v1 message based gov proposal [PR 1321](https://github.com/provenance-io/provenance/pull/1321)
And this shouldn't be down here.

2023-02-13 19:10 UTC, SpicyLemon commented on x/marker/module.go
> +	govKeeper      govkeeper.Keeper
I think you want `types.GovKeeper` here (and as an argument to `NewAppModule`. That way, this module (or at least this file) doesn't have a direct dependency on the gov module.

2023-02-13 19:15 UTC, SpicyLemon commented on x/marker/simulation/operations.go
> +	appParams simtypes.AppParams, cdc codec.JSONCodec, protoCodec *codec.ProtoCodec, k keeper.Keeper, ak authkeeper.AccountKeeper, bk bankkeeper.Keeper, gk govkeeper.Keeper,
Here too with the `types.GovKeeper` interface.

2023-02-13 22:11 UTC, nullpointer0x00 requested changes
We should add a cli to submit a gov proposal tx.

2023-02-14 17:56 UTC, nullpointer0x00 submitted a review, later dismissed

2023-02-17 20:36 UTC, nullpointer0x00 approved these changes

2023-04-10 22:51 UTC, SpicyLemon commented on proto/provenance/marker/v1/tx.proto
> +  [(gogoproto.nullable) = false, (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Coin"];
IntelliJ annoyingly removes those spaces, but they should be there.

2023-04-10 22:54 UTC, SpicyLemon approved these changes
Approving even though there's conflicts that'll dismiss it. But it looks good right now.

2023-04-12 15:46 UTC, SpicyLemon commented
I've copied this branch into one in this repo, and fixed it up a bit: [dwedul/add-marker-proposal](https://github.com/provenance-io/provenance/compare/dwedul/add-marker-proposal). It's not yet ready for a PR, but I'm going to close this PR now anyway.

2023-04-12 15:46 UTC, closed without merging