Add proto messages and type extensions
provenance-io/provenance pull request #353
Opened 2021-06-15 16:42 UTC by channa-figure

## Description

Add/Remove contract spec from scope spec.

closes: #302 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2021-06-22 19:23 UTC, iramiller requested changes
A few comments.  Also see the signer requirement comments.  It is not required to sign with contract spec owners as the contract spec is not being modified here.

2021-06-22 19:23 UTC, iramiller commented on x/metadata/client/cli/tx.go
> +			if err != nil {
```suggestion
			if err != nil || !contractSpecID.IsContractSpecificationAddress(){
```
Should verify parameter is a contract spec address. note: will need to handle/create an error for this to use with following line

2021-06-22 19:23 UTC, iramiller commented on x/metadata/client/cli/tx.go
> +			if err != nil {
```suggestion
			if err != nil || !scopeSpecID.IsScopeSpecificationAddress() {
```
verify address type is scope specification. note: will need to handle/create an error for this to use with following line

2021-06-22 19:23 UTC, iramiller commented on x/metadata/client/cli/tx.go
> +			if err != nil {
```suggestion
			if err != nil  || !contractSpecID.IsContractSpecificationAddress() {
```
verify address type... note: will need to handle/create an error for this to use with following line

2021-06-22 19:23 UTC, iramiller commented on x/metadata/client/cli/tx.go
> +			if err != nil {
```suggestion
			if err != nil || !scopeSpecID.IsScopeSpecificationAddress()  {
```
verify type is scope specification adddress, note: will need to handle/create an error for this to use with following line

2021-06-22 19:23 UTC, iramiller commented on x/metadata/keeper/msg_server.go
> +	if err := k.ValidateAllOwnersAreSigners(contractSpec.OwnerAddresses, msg.Signers); err != nil {
the object being updated is the scope specification ... not the contract specification.  The contract specification owners are not required to sign as their object is not changing.

2021-06-22 19:23 UTC, iramiller commented on x/metadata/keeper/msg_server.go
> +	if err := k.ValidateAllOwnersAreSigners(contractSpec.OwnerAddresses, msg.Signers); err != nil {
contract spec is not being modified here so its owners are not required to sign this update.

2021-06-22 19:23 UTC, iramiller commented on x/metadata/types/msg.go
> +	return nil
consider adding validation of the metadata address format and type here.

2021-06-22 19:23 UTC, iramiller commented on x/metadata/types/msg.go
> +	return nil
consider adding validation of the metadata address format and type here

2021-06-22 21:07 UTC, channa-figure commented
@iramiller thanks for the detailed review.  I got implemented those changes and wrote/updated tests.

2021-06-22 23:01 UTC, iramiller approved these changes
Those cli commands are pretty ugly/long but then again I don't really see them being used very often.

2021-06-23 00:30 UTC, channa-figure commented on x/metadata/client/cli/tx.go
> +		Use:     "remove-contract-spec-to-scope-spec contract-specification-id scope-specification-id",
🤦 Good catch!

2021-06-23 00:30 UTC, channa-figure commented
I agree that the command names are long and ugly.  I stared at them for a while wondering how I could shorten them and have them make sense.  However, I came to the conclusion that they probably won't be used too often.  I added an alias to both the commands to shorten what needs to be typed.

2021-06-23 14:52 UTC, iramiller approved these changes
LGTM.

2021-06-23 16:44 UTC, merged