Makefile check versions of golang
provenance-io/provenance pull request #499
Opened 2021-09-21 20:57 UTC by fkneeland-figure

## Description

closes: #483 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2021-09-22 17:37 UTC, channa-figure requested changes

2021-09-22 18:13 UTC, fkneeland-figure commented on Makefile
> +
@channa-figure done!

2021-09-22 21:17 UTC, fkneeland-figure commented
@channa-figure this is ready for another review

2021-09-22 21:36 UTC, channa-figure approved these changes
LGTM.  This is a very useful addition!

2021-09-23 15:22 UTC, fkneeland-figure commented
Would someone with merge permissions be able to merge this?  Looks like the auto merge got held up on tests not running.

@arnabmitra @iramiller @dwedul-figure

2021-09-28 14:45 UTC, merged